### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by heron2014** [DRDD2016/api#26]
- [ ] PATCH events/event_id (edit)
- [ ] DELETE events/event_id 
- [ ] investigate calendar/albums endpoint - GET events/user_id (list events specific for the user)
- [ ] PATCH users/user_id
- [ ] GET users/user_id
- [ ] GET events/event_id
- [ ] event code feature
- [ ] validation for email and password
- [ ] feed feature
- [ ] save invitees (PATCH events/event_id/invitees?)
